### ISSUE TITLE
Port to enquirer 2

### ISSUE THREAD

**Issue by sebald** [enquirer/prompt-editor#3]
Hey! I just wanted to use this prompt with the latest `enquirer` version, but it doesn't seem to be compatible anymore. Are there any plans to add this to the new `enquirer`? 🙂

**Comment by jonschlinkert** [comment]
I would definitely like to update this prompt to use the Enquirer 2.0 API, but there are no plans for this prompt to ship with Enquirer. 

I'd happily accept a PR for a refactor here!

**Comment by sebald** [comment]
I already started, but have trouble with the "internal" prompt API. Could you point me to a document? 🙂

**Comment by sebald** [comment]
Hey, I published this here: https://www.npmjs.com/package/enquirer-prompt-editor
It's a start at least and I wanted to finish something before 🎄

**Comment by jonschlinkert** [comment]
A duplicate?

**Comment by sebald** [comment]
It works with enquirer 2.x but is not prompt agnostic.

**Comment by sebald** [comment]
Please don't feel offended or anything by me publishing this as a new package. I am happy to transfer ownership.

I wanted to use it immediately and publishing (instead of using fit as an mom source) semmed the easiest way.

**Comment by jonschlinkert** [comment]
> Please don't feel offended or anything by me publishing this as a new package. I am happy to transfer ownership.

No need, we have a prompt-editor library already. It's ok.

**Comment by zkochan** [comment]
So what is the outcome? The fork of @sebald should be used to have an editor prompt?
